codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        # basic
        target: 70%
        threshold: 0%
        base: auto
        # advanced settings
        if_ci_failed: error
        only_pulls: false
    patch:
      default:
        # basic
        target: 50%
        threshold: 0%
        base: auto
        # advanced settings
        if_ci_failed: error
        only_pulls: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
  require_base: no